In [19]:
!pip install pandas
import pandas as pd
kc_house_data=pd.read_csv("kc_house_data.csv")
kc_house_data.head()

Requirement already satisfied: pandas in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.24.2)
Requirement already satisfied: six>=1.5 in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [20]:
kc_house_data.drop(['id','date','waterfront','zipcode','view','zipcode','lat','long'],axis=1,inplace=True)

print(kc_house_data)

          price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0      221900.0         3       1.00         1180      5650     1.0
1      538000.0         3       2.25         2570      7242     2.0
2      180000.0         2       1.00          770     10000     1.0
3      604000.0         4       3.00         1960      5000     1.0
4      510000.0         3       2.00         1680      8080     1.0
...         ...       ...        ...          ...       ...     ...
21608  360000.0         3       2.50         1530      1131     3.0
21609  400000.0         4       2.50         2310      5813     2.0
21610  402101.0         2       0.75         1020      1350     2.0
21611  400000.0         3       2.50         1600      2388     2.0
21612  325000.0         2       0.75         1020      1076     2.0

       condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0              3      7        1180              0      1955             0
1              3      7        2170            400      1951          1991
2              3      6         770              0      1933             0
3              5      7        1050            910      1965             0
4              3      8        1680              0      1987             0
...          ...    ...         ...            ...       ...           ...
21608          3      8        1530              0      2009             0
21609          3      8        2310              0      2014             0
21610          3      7        1020              0      2009             0
21611          3      8        1600              0      2004             0
21612          3      7        1020              0      2008             0

       sqft_living15  sqft_lot15
0               1340        5650
1               1690        7639
2               2720        8062
3               1360        5000
4               1800        7503
...              ...         ...
21608           1530        1509
21609           1830        7200
21610           1020        2007
21611           1410        1287
21612           1020        1357

[21613 rows x 14 columns]

In [25]:
kc_house_data.isnull().sum()

price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [29]:
X=kc_house_data.drop(['price'],axis=1)
Y=kc_house_data['price']

In [30]:
!pip install numpy
import numpy as np
kc_house_data.select_dtypes(np.number)

Requirement already satisfied: numpy in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (1.24.2)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,sqft_living15,sqft_lot15
0,221900.0,3,1.00,1180,5650,1.0,3,7,1180,0,1955,0,1340,5650
1,538000.0,3,2.25,2570,7242,2.0,3,7,2170,400,1951,1991,1690,7639
2,180000.0,2,1.00,770,10000,1.0,3,6,770,0,1933,0,2720,8062
3,604000.0,4,3.00,1960,5000,1.0,5,7,1050,910,1965,0,1360,5000
4,510000.0,3,2.00,1680,8080,1.0,3,8,1680,0,1987,0,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,360000.0,3,2.50,1530,1131,3.0,3,8,1530,0,2009,0,1530,1509
21609,400000.0,4,2.50,2310,5813,2.0,3,8,2310,0,2014,0,1830,7200
21610,402101.0,2,0.75,1020,1350,2.0,3,7,1020,0,2009,0,1020,2007
21611,400000.0,3,2.50,1600,2388,2.0,3,8,1600,0,2004,0,1410,1287
21612,325000.0,2,0.75,1020,1076,2.0,3,7,1020,0,2008,0,1020,1357

In [31]:
X=kc_house_data.drop(['price'],axis=1)
Y=kc_house_data['price']

In [33]:
X_train=np.array(X[0:int(0.80*len(X))])
Y_train=np.array(Y[0:int(0.80*len(Y))])

In [35]:
X_test=np.array(X[int(0.80*len(X)):])
Y_test=np.array(Y[int(0.80*len(Y)):])
len(X_train),len(X_test),len(Y_test)

(17290, 4323, 4323)

In [38]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR_fit=LR.fit(X_train,Y_train)
LR_pred=LR_fit.predict(X_test)
from sklearn.metrics import accuracy_score
print("Logisitic Regression is %f percent accurate"%(accuracy_score(LR_pred,Y_test)*100))

Logisitic Regression is 0.416378 percent accurate

c:\Users\toyes\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [40]:
from sklearn.naive_bayes import GaussianNB
NB=GaussianNB()
NB_fit=NB.fit(X_train,Y_train)
NB_pred=NB_fit.predict(X_test)
from sklearn.metrics import accuracy_score
print("Naive Bayes is %f percent accurate"%(accuracy_score(NB_pred,Y_test)*100))

Naive Bayes is 0.000000 percent accurate

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
seed=0
cv= KFold(n_splits=5,random_state=2, shuffle=True)

In [60]:
def return_score(model,X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    score = model.score(X_test, y_test)
    return score
scores = []

In [61]:
model = LogisticRegression()
for train_index, test_index in cv.split(X,Y):
    X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2)
    score = return_score(model,X_train, X_test, y_train, y_test)
    scores.append(score)
print("Accuracy score in each iteration: {}".format(scores))
print ("K-Fold Score: {}".format(np.mean(scores)))

c:\Users\toyes\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\toyes\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\toyes\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\toyes\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Accuracy score in each iteration: [0.006939625260235947, 0.005320379366180893, 0.006476983576220218, 0.006476983576220218, 0.009252833680314597]
K-Fold Score: 0.006893361091834374

c:\Users\toyes\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [62]:
model = GaussianNB()
for train_index, test_index in cv.split(X,Y):
    X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2)
    score = return_score(model,X_train, X_test, y_train, y_test)
    scores.append(score)
print("Accuracy score in each iteration: {}".format(scores))
print("K-Fold Score: {}".format(np.mean(scores)))

Accuracy score in each iteration: [0.006939625260235947, 0.005320379366180893, 0.006476983576220218, 0.006476983576220218, 0.009252833680314597, 0.0, 0.0009252833680314596, 0.0006939625260235947, 0.0006939625260235947, 0.0004626416840157298]
K-Fold Score: 0.0037242655563266254