In [17]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.24.2)
Requirement already satisfied: six>=1.5 in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [18]:
kc_house_data=pd.read_csv("kc_house_data.csv")
kc_house_data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [20]:
kc_house_data.drop(['view','grade','sqft_above','sqft_basement','yr_built','yr_renovated','zipcode','lat','long','sqft_living15','sqft_lot15'], axis=1, inplace=True)
print(kc_house_data)

                  date     price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0      20141013T000000  221900.0         3       1.00         1180      5650
1      20141209T000000  538000.0         3       2.25         2570      7242
2      20150225T000000  180000.0         2       1.00          770     10000
3      20141209T000000  604000.0         4       3.00         1960      5000
4      20150218T000000  510000.0         3       2.00         1680      8080
...                ...       ...       ...        ...          ...       ...
21608  20140521T000000  360000.0         3       2.50         1530      1131
21609  20150223T000000  400000.0         4       2.50         2310      5813
21610  20140623T000000  402101.0         2       0.75         1020      1350
21611  20150116T000000  400000.0         3       2.50         1600      2388
21612  20141015T000000  325000.0         2       0.75         1020      1076

       floors  condition
0         1.0          3
1         2.0          3
2         1.0          3
3         1.0          5
4         1.0          3
...       ...        ...
21608     3.0          3
21609     2.0          3
21610     2.0          3
21611     2.0          3
21612     2.0          3

[21613 rows x 8 columns]

In [21]:
!pip install scikit-learn
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
kc_house_data = kc_house_data.apply(le.fit_transform)

Requirement already satisfied: scikit-learn in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.24.2)
Requirement already satisfied: scipy>=1.3.2 in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\toyes\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.1.0)